<?php
session_start();

// Serve graph images generated by ../model/Regression_Linear.py.
if (isset($_GET['graph'])) {
    $allowedGraphs = [
        'fish' => 'regression_fish.png'
    ];

    $graphKey = (string)$_GET['graph'];
    if (!isset($allowedGraphs[$graphKey])) {
        http_response_code(404);
        exit('Graph not found');
    }

    $outputDirectory = realpath(
        __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR .
        'model' . DIRECTORY_SEPARATOR . 'output'
    );

    $graphPath = realpath(
        __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR .
        'model' . DIRECTORY_SEPARATOR . 'output' . DIRECTORY_SEPARATOR .
        $allowedGraphs[$graphKey]
    );

    if (
        $outputDirectory === false ||
        $graphPath === false ||
        strpos($graphPath, $outputDirectory) !== 0 ||
        !is_file($graphPath)
    ) {
        http_response_code(404);
        exit('Graph file not found');
    }

    header('Content-Type: image/png');
    header('Content-Length: ' . filesize($graphPath));
    header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
    readfile($graphPath);
    exit();
}

function h($value): string
{
    return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
}

function extract_json($text): ?array
{
    $text = trim((string)$text);

    $decoded = json_decode($text, true);
    if (is_array($decoded)) {
        return $decoded;
    }

    // Fallback: read from the last line upward. This also allows Python
    // warnings to appear before the final JSON response.
    $lines = preg_split('/\R/', $text);
    if (is_array($lines)) {
        for ($index = count($lines) - 1; $index >= 0; $index--) {
            $line = trim($lines[$index]);
            if ($line === '') {
                continue;
            }

            $decoded = json_decode($line, true);
            if (is_array($decoded)) {
                return $decoded;
            }
        }
    }

    return null;
}

function metric_value($value, int $decimals = 4, string $suffix = ''): string
{
    if ($value === null || $value === '' || !is_numeric($value)) {
        return '-';
    }

    return number_format((float)$value, $decimals) . $suffix;
}

function run_regression_python(array $arguments, ?string &$rawOutput, ?string &$error): ?array
{
    $python = getenv('PROJECTA_PYTHON') ?: 'python';
    $script = realpath(
        __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR .
        'model' . DIRECTORY_SEPARATOR . 'Regression_Linear.py'
    );

    if ($script === false || !is_file($script)) {
        $error = 'ไม่พบไฟล์ Regression_Linear.py ในโฟลเดอร์ model';
        return null;
    }

    if (!function_exists('shell_exec')) {
        $error = 'PHP ปิดการใช้งาน shell_exec()';
        return null;
    }

    $commandParts = [
        escapeshellcmd($python),
        escapeshellarg($script)
    ];

    foreach ($arguments as $argument) {
        $commandParts[] = escapeshellarg((string)$argument);
    }

    $command = implode(' ', $commandParts) . ' 2>&1';
    $rawOutput = shell_exec($command);

    if ($rawOutput === null || trim($rawOutput) === '') {
        $error = 'ไม่สามารถเรียก Python ได้ กรุณาตรวจสอบ Python, shell_exec() และ package ที่จำเป็น';
        return null;
    }

    $decoded = extract_json($rawOutput);

    if (!is_array($decoded)) {
        $error = 'Python ไม่ได้ส่งข้อมูลกลับมาเป็น JSON';
        return null;
    }

    if (($decoded['status'] ?? '') !== 'success') {
        $error = $decoded['message'] ?? 'เกิดข้อผิดพลาดจากโมเดล';
        return null;
    }

    return $decoded;
}

$months = [
    1 => 'มกราคม',
    2 => 'กุมภาพันธ์',
    3 => 'มีนาคม',
    4 => 'เมษายน',
    5 => 'พฤษภาคม',
    6 => 'มิถุนายน',
    7 => 'กรกฎาคม',
    8 => 'สิงหาคม',
    9 => 'กันยายน',
    10 => 'ตุลาคม',
    11 => 'พฤศจิกายน',
    12 => 'ธันวาคม'
];

// The current ML data contains these 5 stations.
$provinceList = [
    'เพชรบุรี',
    'สมุทรสงคราม',
    'สมุทรสาคร',
    'ชลบุรี',
    'สมุทรปราการ'
];

// Normal database prediction form defaults.
$selectedMonth = (string)($_POST['month'] ?? '10');
$selectedYear = (string)($_POST['year'] ?? '2568');
$selectedProvince = (string)($_POST['province'] ?? 'สมุทรปราการ');

// Custom SST / Chlorophyll-a / SSS form defaults.
$customMonth = (string)($_POST['custom_month'] ?? '10');
$customYear = (string)($_POST['custom_year'] ?? '2568');
$customProvince = (string)($_POST['custom_province'] ?? 'สมุทรปราการ');
$customSst = (string)($_POST['custom_sst'] ?? '29.00');
$customChlor = (string)($_POST['custom_chlor_a'] ?? '5.00');
$customSss = (string)($_POST['custom_sss'] ?? '25.00');

$dbResult = null;
$customResult = null;
$activeResult = null;
$error = null;
$rawOutput = null;
$action = (string)($_POST['action'] ?? '');

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if ($action === 'custom_predict') {
        $province = trim((string)($_POST['custom_province'] ?? ''));
        $year = (int)($_POST['custom_year'] ?? 0);
        $month = (int)($_POST['custom_month'] ?? 0);
        $sst = filter_var($_POST['custom_sst'] ?? null, FILTER_VALIDATE_FLOAT);
        $chlor = filter_var($_POST['custom_chlor_a'] ?? null, FILTER_VALIDATE_FLOAT);
        $sss = filter_var($_POST['custom_sss'] ?? null, FILTER_VALIDATE_FLOAT);

        $customProvince = $province;
        $customYear = (string)$year;
        $customMonth = (string)$month;
        $customSst = (string)($_POST['custom_sst'] ?? '');
        $customChlor = (string)($_POST['custom_chlor_a'] ?? '');
        $customSss = (string)($_POST['custom_sss'] ?? '');

        if (
            !in_array($province, $provinceList, true) ||
            $year < 2562 || $year > 2569 ||
            $month < 1 || $month > 12 ||
            $sst === false || (float)$sst <= 0 ||
            $chlor === false || (float)$chlor <= 0 ||
            $sss === false || (float)$sss <= 0
        ) {
            $error = 'กรุณากรอกจังหวัด ปี เดือน SST, Chlorophyll-a และ SSS ให้ถูกต้อง';
        } else {
            $provinceBase64 = base64_encode($province);

            $customResult = run_regression_python(
                [
                    '--custom',
                    $provinceBase64,
                    (string)$year,
                    (string)$month,
                    (string)$sst,
                    (string)$chlor,
                    (string)$sss,
                    '--b64'
                ],
                $rawOutput,
                $error
            );

            $activeResult = $customResult;
        }
    } else {
        $province = trim((string)($_POST['province'] ?? ''));
        $year = (int)($_POST['year'] ?? 0);
        $month = (int)($_POST['month'] ?? 0);

        $selectedProvince = $province;
        $selectedYear = (string)$year;
        $selectedMonth = (string)$month;

        if (
            !in_array($province, $provinceList, true) ||
            $year < 2562 || $year > 2569 ||
            $month < 1 || $month > 12
        ) {
            $error = 'กรุณาเลือกจังหวัด ปี (2562-2569) และเดือนให้ถูกต้อง';
        } else {
            $provinceBase64 = base64_encode($province);

            // Keep the original argument format for backwards compatibility:
            // <province_b64> <year> <month> --b64
            $dbResult = run_regression_python(
                [
                    $provinceBase64,
                    (string)$year,
                    (string)$month,
                    '--b64'
                ],
                $rawOutput,
                $error
            );

            $activeResult = $dbResult;
        }
    }
}

$activeModel = $activeResult['model'] ?? [];
$validationMetrics = $activeModel['validation_metrics'] ?? [];
$overallMetrics = $activeModel['overall_metrics'] ?? [];
?>

<!DOCTYPE html>
<html lang="th">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Linear Regression</title>

    <link rel="icon" type="image/png" href="../img/logo.png">

    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
    >
    <link rel="stylesheet" href="../css/menu.css">
    <link rel="stylesheet" href="../css/data.css">

    <style>
        .metric-card {
            border: 1px solid rgba(0, 0, 0, 0.08);
            border-radius: 12px;
            height: 100%;
            padding: 18px;
            background: #fff;
        }
        .metric-value {
            font-size: 1.45rem;
            font-weight: 700;
            margin-bottom: 0;
        }
        .result-box {
            border-radius: 12px;
            background: #f8f9fa;
            border: 1px solid #e9ecef;
            padding: 18px;
        }
        .custom-card {
            border-left: 5px solid #6f42c1;
        }
        .custom-card .card-header {
            color: #000 !important;
            font-size: 1.6rem;
            font-weight: 700;
        }
    </style>
</head>

<body>
<?php include 'menu.php'; ?>

<div class="container page-container">

    <div class="page-header mb-4">
        <h2>Linear Regression</h2>
        <p class="text-muted mb-0">
            Predict Mackerel Distribution Density
        </p>
    </div>

    <!-- 1) Prediction using values stored in Database -->
    <div class="card shadow-sm border-0 mb-4">
        <div class="card-header">การคาดการณ์จากข้อมูลในฐานข้อมูล</div>
        <div class="card-body">
            <form method="post">
                <input type="hidden" name="action" value="db_predict">

                <div class="row">
                    <div class="col-md-4 mb-3">
                        <label class="form-label">เดือน</label>
                        <select class="form-select" name="month" required>
                            <?php foreach ($months as $number => $monthName): ?>
                                <option
                                    value="<?= h($number) ?>"
                                    <?= (int)$selectedMonth === (int)$number ? 'selected' : '' ?>
                                >
                                    <?= h($monthName) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <div class="col-md-4 mb-3">
                        <label class="form-label">ปี (พ.ศ. 2562-2569)</label>
                        <input
                            type="number"
                            class="form-control"
                            name="year"
                            value="<?= h($selectedYear) ?>"
                            min="2562"
                            max="2569"
                            required
                        >
                    </div>

                    <div class="col-md-4 mb-3">
                        <label class="form-label">จังหวัด</label>
                        <select class="form-select" name="province" required>
                            <?php foreach ($provinceList as $provinceName): ?>
                                <option
                                    value="<?= h($provinceName) ?>"
                                    <?= $selectedProvince === $provinceName ? 'selected' : '' ?>
                                >
                                    <?= h($provinceName) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <button class="btn btn-primary" type="submit">แสดงผล</button>
            </form>
        </div>
    </div>

    <?php if ($error): ?>
        <div class="alert alert-danger">
            <strong>Error:</strong> <?= h($error) ?>

            <?php if ($rawOutput): ?>
                <hr>
                <pre class="mb-0 small text-wrap"><?= h($rawOutput) ?></pre>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <?php if ($dbResult): ?>
        <div class="card shadow-sm border-0 mb-4">
            <div class="card-header bg-primary text-white">
                ผลลัพธ์การคาดการณ์จากฐานข้อมูล
            </div>

            <div class="card-body">
                <div class="row text-center">
                    <div class="col-md-3 mb-3">
                        <h6 class="text-muted">Predicted Mackerel Catch</h6>
                        <h1 class="result-value text-primary">
                            <?= number_format((float)$dbResult['ton'], 2) ?>
                        </h1>
                        <p class="text-muted">Ton</p>
                    </div>

                    <div class="col-md-3 mb-3">
                        <h6 class="text-muted">SST</h6>
                        <h1 class="result-value text-success">
                            <?= number_format((float)$dbResult['sst'], 2) ?>
                        </h1>
                        <p class="text-muted">°C</p>
                    </div>

                    <div class="col-md-3 mb-3">
                        <h6 class="text-muted">Chlorophyll-a</h6>
                        <h1 class="result-value text-warning">
                            <?= number_format((float)$dbResult['chlor_a'], 2) ?>
                        </h1>
                        <p class="text-muted">mg/m³</p>
                    </div>

                    <div class="col-md-3 mb-3">
                        <h6 class="text-muted">SSS</h6>
                        <h1 class="result-value text-info">
                            <?= number_format((float)($dbResult['sss'] ?? 0), 2) ?>
                        </h1>
                        <p class="text-muted mb-1">PSU</p>
                    </div>
                </div>

                <div class="text-center text-muted">
                    จังหวัด <?= h($dbResult['province']) ?>,
                    ปี <?= h($dbResult['year']) ?>,
                    เดือน <?= h($months[(int)$dbResult['month']] ?? $dbResult['month']) ?>
                </div>

                <div class="text-center text-muted small mt-2">
                    Rainfall <?= number_format((float)$dbResult['rainfall'], 2) ?> ·
                    Wind Speed <?= number_format((float)$dbResult['wind_speed'], 2) ?>
                </div>

                <?php if (($dbResult['actual_ton'] ?? null) !== null): ?>
                    <div class="text-center mt-2">
                        Actual:
                        <strong><?= number_format((float)$dbResult['actual_ton'], 2) ?> ton</strong>
                        · Difference:
                        <strong><?= number_format(abs((float)$dbResult['ton'] - (float)$dbResult['actual_ton']), 2) ?> ton</strong>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>

    <!-- กราฟ Actual vs Prediction -->
    <div class="card shadow-sm border-0 mb-4">
        <div class="card-header">กราฟ Actual vs Prediction รายเดือน</div>
        <div class="card-body text-center">
            <?php if ($dbResult && !empty($dbResult['graphs_generated'])): ?>
                <h4>Mackerel Catch</h4>
                <img
                    src="regression.php?graph=fish&amp;v=<?= time() ?>"
                    class="img-fluid mb-4"
                    alt="Mackerel catch graph"
                >
            <?php elseif ($dbResult): ?>
                <div class="graph-placeholder">
                    คำนวณผลสำเร็จ แต่ไม่สามารถสร้างกราฟได้ กรุณาตรวจสอบ matplotlib
                </div>
            <?php else: ?>
                <div class="graph-placeholder">
                    เลือกเดือน ปี จังหวัด แล้วกดแสดงผลเพื่อสร้างกราฟ
                </div>
            <?php endif; ?>
        </div>
    </div>

    <!-- 2) New custom SST/Chlorophyll-a prediction -->
    <div class="card shadow-sm border-0 mb-4">
        <div class="card-header">กำหนดค่า SST, Chlorophyll-a และ SSS เอง</div>

        <div class="card-body">
            <p class="text-muted">
                กำหนด จังหวัด เดือน ปี SST, Chlorophyll-a และ SSS ด้วยตนเอง
                ส่วน Rainfall และ Wind Speed ระบบจะดึงจาก weather_data ตามช่วงเวลาที่เลือกโดยอัตโนมัติ
            </p>

            <form method="post">
                <input type="hidden" name="action" value="custom_predict">

                <div class="row">
                    <div class="col-lg-4 col-md-6 mb-3">
                        <label class="form-label">จังหวัด</label>
                        <select class="form-select" name="custom_province" required>
                            <?php foreach ($provinceList as $provinceName): ?>
                                <option
                                    value="<?= h($provinceName) ?>"
                                    <?= $customProvince === $provinceName ? 'selected' : '' ?>
                                >
                                    <?= h($provinceName) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <div class="col-lg-4 col-md-6 mb-3">
                        <label class="form-label">เดือน</label>
                        <select class="form-select" name="custom_month" required>
                            <?php foreach ($months as $number => $monthName): ?>
                                <option
                                    value="<?= h($number) ?>"
                                    <?= (int)$customMonth === (int)$number ? 'selected' : '' ?>
                                >
                                    <?= h($monthName) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <div class="col-lg-4 col-md-6 mb-3">
                        <label class="form-label">ปี (พ.ศ. 2562-2569)</label>
                        <input
                            type="number"
                            class="form-control"
                            name="custom_year"
                            min="2562"
                            max="2569"
                            value="<?= h($customYear) ?>"
                            required
                        >
                    </div>

                    <div class="col-lg-4 col-md-6 mb-3">
                        <label class="form-label">SST (°C)</label>
                        <input
                            type="number"
                            step="0.01"
                            min="0.01"
                            class="form-control"
                            name="custom_sst"
                            value="<?= h($customSst) ?>"
                            required
                        >
                    </div>

                    <div class="col-lg-4 col-md-6 mb-3">
                        <label class="form-label">Chlorophyll-a (mg/m³)</label>
                        <input
                            type="number"
                            step="0.01"
                            min="0.01"
                            class="form-control"
                            name="custom_chlor_a"
                            value="<?= h($customChlor) ?>"
                            required
                        >
                    </div>

                    <div class="col-lg-4 col-md-6 mb-3">
                        <label class="form-label">SSS (PSU)</label>
                        <input
                            type="number"
                            step="0.01"
                            min="0.01"
                            class="form-control"
                            name="custom_sss"
                            value="<?= h($customSss) ?>"
                            required
                        >
                    </div>
                </div>

                <button class="btn btn-outline-primary" type="submit">
                    คำนวณจากค่าที่กำหนด
                </button>
            </form>

            <?php if ($customResult): ?>
                <hr class="my-4">

                <div class="result-box">
                    <div class="row align-items-center">
                        <div class="col-md-5 text-center mb-3 mb-md-0">
                            <div class="text-muted">Predicted Mackerel Catch</div>
                            <div class="display-5 fw-bold text-primary">
                                <?= number_format((float)$customResult['ton'], 2) ?>
                            </div>
                            <div class="text-muted">Ton</div>
                        </div>

                        <div class="col-md-7">
                            <div>
                                <strong>จังหวัด:</strong> <?= h($customResult['province']) ?>
                            </div>
                            <div>
                                <strong>ปี / เดือน:</strong>
                                <?= h($customResult['year']) ?> /
                                <?= h($months[(int)$customResult['month']] ?? $customResult['month']) ?>
                            </div>
                            <div>
                                <strong>SST:</strong>
                                <?= number_format((float)$customResult['sst'], 2) ?> °C
                            </div>
                            <div>
                                <strong>Chlorophyll-a:</strong>
                                <?= number_format((float)$customResult['chlor_a'], 2) ?> mg/m³
                            </div>
                            <div>
                                <strong>SSS:</strong>
                                <?= number_format((float)($customResult['sss'] ?? 0), 2) ?> PSU
                            </div>
                            <div>
                                <strong>Rainfall ที่โมเดลใช้:</strong>
                                <?= number_format((float)$customResult['rainfall'], 2) ?>
                            </div>
                            <div>
                                <strong>Wind Speed ที่โมเดลใช้:</strong>
                                <?= number_format((float)$customResult['wind_speed'], 2) ?>
                            </div>
                            <div class="small text-muted mt-2">
                                Weather source: <?= h($customResult['weather_source'] ?? '-') ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>

    <!-- Performance: only MAE / RMSE / R² as requested. -->
    <div class="card shadow-sm border-0 mb-4">
        <div class="card-header bg-dark text-white">
            Linear Regression Performance
        </div>

        <div class="card-body">
            <?php if (!$activeResult): ?>
                <div class="text-muted text-center py-4">
                    กดแสดงผลจากฐานข้อมูล หรือคำนวณจากค่าที่กำหนด เพื่อแสดงประสิทธิภาพ
                </div>
            <?php else: ?>
                <div class="text-center mb-3">
                    <strong><?= h($activeResult['province'] ?? '-') ?></strong>
                    <span class="text-muted">
                        · Test ปี <?= h($activeModel['holdout_year'] ?? '-') ?>
                    </span>
                </div>

                <div class="row g-3 justify-content-center">
                    <div class="col-md-4">
                        <div class="metric-card text-center">
                            <div class="text-muted small">MAE</div>
                            <p class="metric-value">
                                <?= metric_value($validationMetrics['mae'] ?? null, 2, ' ton') ?>
                            </p>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="metric-card text-center">
                            <div class="text-muted small">RMSE</div>
                            <p class="metric-value">
                                <?= metric_value($validationMetrics['rmse'] ?? null, 2, ' ton') ?>
                            </p>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="metric-card text-center">
                            <div class="text-muted small">R² Overall</div>
                            <p class="metric-value">
                                <?= metric_value($overallMetrics['r2'] ?? null, 4) ?>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="text-center text-muted small mt-3">
                    MAE และ RMSE เป็นผลของจังหวัดที่เลือก ส่วน R² แสดงค่า Overall ของทั้ง 5 จังหวัด
                    เพื่อประเมินภาพรวมจากชุด Test ที่มีจำนวนตัวอย่างมากกว่า 12 เดือนของจังหวัดเดียว
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<?php include 'footer.php'; ?>

<script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
></script>
</body>
</html>
